name: Unit Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['12.x', '14.x']
        language: [ 'javascript' ]

    name: Test on node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install deps, build, and test
        run: |
          node --version
          npm --version
          yarn --version        
          yarn install --frozen-lockfile
          yarn test --coverage
        env:
          CI: true
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
